# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:28:35+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header

from models import (
    AddressAutocompletePostRequest,
    ContactEnrichPostRequest,
    EmailEnrichPostRequest,
    IdentityVerifyIdPostRequest,
    PhoneEnrichPostRequest,
)

app = MCPProxy(
    description='Self Service Developer API documentation and demo.\n\n##Getting Started\n\nYou will need an API access profile user and password in order to access search endpoints.\nYour access profile user and password is used for authenticating all requests to our search API. \nYou MUST pass the user and password each time you perform a search request.',
    title='Self Service Developer API',
    version='1.0.0',
    servers=[{'url': 'https://api.peoplefinderspro.com'}],
)


@app.post(
    '/address/autocomplete',
    description=""" ###### *Click on the grey search box above, to view sample request/response objects for Address Autocomplete Search*

Perform a search:

1. Add your key and key secret to the request headers.
    + galaxy-ap-name: [Key]
    + galaxy-ap-password: [Secret]
    + galaxy-search-type: DevAPIAddressAutoComplete

2.  Add search criteria to your request.
    ~~~html
            {
                "Input":"1821 Q"
            }
    ~~~

3.  Submit your search

The JSON request should have parts of the address.

+ <code>Input</code> = null (optional, string) ... address. """,
    tags=['address_autocomplete'],
)
def post_address_autocomplete(
    galaxy_ap_name: Optional[str] = Header(None, alias='galaxy-ap-name'),
    galaxy_ap_password: Optional[str] = Header(None, alias='galaxy-ap-password'),
    galaxy_search_type: Optional[str] = Header(None, alias='galaxy-search-type'),
    body: AddressAutocompletePostRequest = None,
):
    """
    Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/contact/enrich',
    description=""" ###### *Click on the grey search box above, to view sample request/response objects for Contact Enrichment Search*

Perform a search:

1. Add your key and key secret to the request headers.
    + galaxy-ap-name: [Key]
    + galaxy-ap-password: [Secret]
    + galaxy-search-type: DevAPIContactEnrich

2.  Add search criteria to your request. At least two are required: Name, Phone, Address, or Email.
    ~~~html
            {
                "FirstName": "John",
                "MiddleName": "T",
                "LastName": "Lawrence",
                "Dob":"",
                "Age": 0,
                "Address": {
                    "addressLine1":"123 Q Street",
                    "addressLine2":"Sacramento, CA"
                },
                "PhoneNumber":"",
                "Email":""
            }
    ~~~

3.  Submit your search

A complete list of JSON request properties follows.

+ <code>FirstName</code>= null (optional, string) ... First name.

+ <code>MiddleName</code> = null (optional, string) ... Middle name or middle initial.

+ <code>LastName</code> = null (optional, string) ... Last name.

+ <code>Dob</code> = null (optional, string) ... Date of birth (format: MM/DD/YYYY).

+ <code>Age</code> = null (optional, int) ... Age.

+ <code>Addresses</code> = null (optional, Addresses[]) ... List of addresses.
    + <code>Members</code>
        + <code>AddressLine1</code> = null (optional, string) ... House number, street name and Unit number (i.e. 123 Q Street, Unit 102) or PO Box (i.e. 1821 Q Street).
        + <code>AddressLine2</code> = null (optional, string) ... State or City and State or Zip (i.e. Sacramento, CA).

+ <code>Phone</code> = null (optional, string) ... Phone number (formats: ###-###-####, (###) ###-####).

+ <code>Email</code> = null (optional, string) ... E-mail address. """,
    tags=['contact_enrichment'],
)
def post_contact_enrich(
    galaxy_ap_name: Optional[str] = Header(None, alias='galaxy-ap-name'),
    galaxy_ap_password: Optional[str] = Header(None, alias='galaxy-ap-password'),
    galaxy_search_type: Optional[str] = Header(None, alias='galaxy-search-type'),
    body: ContactEnrichPostRequest = None,
):
    """
    Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/email/enrich',
    description=""" ###### *Click on the grey search box above, to view sample request/response objects for Email Enrichment Search*

Perform a search:

1. Add your Access Profile username and password to the request headers.
    + galaxy-ap-name: [Key]
    + galaxy-ap-password: [Secret]
    + galaxy-search-type: DevAPIEmailID

2.  Add search criteria to your request.
    ~~~html
            {
                "Email":"johnsmith@somedomain"
            }
    ~~~

3.  Submit your search

The JSON request should have an email.

+ <code>Email</code> = null (optional, string) ... E-mail address. """,
    tags=['email_enrichment', 'contact_enrichment'],
)
def post_email_enrich(
    galaxy_ap_name: Optional[str] = Header(None, alias='galaxy-ap-name'),
    galaxy_ap_password: Optional[str] = Header(None, alias='galaxy-ap-password'),
    galaxy_search_type: Optional[str] = Header(None, alias='galaxy-search-type'),
    body: EmailEnrichPostRequest = None,
):
    """
    Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/identity/verify_id',
    description=""" ###### *Click on the grey search box above, to view sample request/response objects for the Identity Verification Search*

Perform a search:

1. Add your key and key secret to the request headers.
    + galaxy-ap-name: [Key]
    + galaxy-ap-password: [Secret]
    + galaxy-search-type: DevAPIIDVerification

2.  Add search criteria to your request. At least two are required: SSN, Name, Phone, Address or Email.
    ~~~html
            {
                "FirstName": "John",
                "MiddleName": "T",
                "LastName": "Lawrence",
                "Dob":"",
                "Age": 0,
                "Address": {
                    "addressLine1":"123 Q Street, Unit 102",
                    "addressLine2":"Sacramento, CA"
                },
                "PhoneNumber":"",
                "Email":""
            }
    ~~~

3.  Submit your search

A complete list of JSON request properties follows.

+ <code>FirstName</code>= null (optional, string) ... First name.

+ <code>MiddleName</code> = null (optional, string) ... Middle name or middle initial.

+ <code>LastName</code> = null (optional, string) ... Last name.

+ <code>Dob</code> = null (optional, string) ... Date of birth (format: MM/DD/YYYY).

+ <code>Age</code> = null (optional, int) ... Age.

+ <code>Addresses</code> = null (optional, Addresses[]) ... List of addresses.
    + <code>Members</code>
        + <code>AddressLine1</code> = null (optional, string) ... House number, street name and Unit number (i.e. 123 Q Street, Unit 102) or PO Box (i.e. 1821 Q Street).
        + <code>AddressLine2</code> = null (optional, string) ... State or City and State or Zip (i.e. Sacramento, CA).

+ <code>Phone</code> = null (optional, string) ... Phone number (formats: ###-###-####, (###) ###-####).

+ <code>Email</code> = null (optional, string) ... E-mail address. """,
    tags=['identity_verification'],
)
def search(
    galaxy_ap_name: Optional[str] = Header(None, alias='galaxy-ap-name'),
    galaxy_ap_password: Optional[str] = Header(None, alias='galaxy-ap-password'),
    galaxy_search_type: Optional[str] = Header(None, alias='galaxy-search-type'),
    body: IdentityVerifyIdPostRequest = None,
):
    """
    Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/phone/enrich',
    description=""" ###### *Click on the grey search box above, to view sample request/response objects for Phone Enrichment Search*

Perform a search:

1. Add your key and key secret to the request headers.
    + galaxy-ap-name: [Key]
    + galaxy-ap-password: [Secret]
    + galaxy-search-type: DevAPICallerID

2.  Add search criteria to your request.
    ~~~html
            {
                "Phone":"(123) 456-7890"
            }
    ~~~

3.  Submit your search

The JSON request should have a phone number.

+ <code>Phone</code> = null (optional, string) ... Phone number (formats: ###-###-####, (###) ###-####). """,
    tags=['contact_enrichment', 'phone_number_enrichment'],
)
def post_phone_enrich(
    galaxy_ap_name: Optional[str] = Header(None, alias='galaxy-ap-name'),
    galaxy_ap_password: Optional[str] = Header(None, alias='galaxy-ap-password'),
    galaxy_search_type: Optional[str] = Header(None, alias='galaxy-search-type'),
    body: PhoneEnrichPostRequest = None,
):
    """
    Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
