# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:28:35+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field, RootModel


class AddressAutoComplete(RootModel[Any]):
    root: Any


class CallerID(RootModel[Any]):
    root: Any


class ContactEnrichment(RootModel[Any]):
    root: Any


class EmailID(RootModel[Any]):
    root: Any


class IDVerification(RootModel[Any]):
    root: Any


class AddressAutocompletePostRequest(BaseModel):
    Input: Optional[str] = None


class Address(BaseModel):
    addressLine1: Optional[str] = None
    addressLine2: Optional[str] = None


class ContactEnrichPostRequest(BaseModel):
    Address_1: Optional[Address] = Field(None, alias='Address')
    Age: Optional[float] = None
    Dob: Optional[str] = None
    Email: Optional[str] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    MiddleName: Optional[str] = None
    PhoneNumber: Optional[str] = None


class EmailEnrichPostRequest(BaseModel):
    Email: Optional[str] = None


class IdentityVerifyIdPostRequest(BaseModel):
    Address_1: Optional[Address] = Field(None, alias='Address')
    Age: Optional[float] = None
    Dob: Optional[str] = None
    Email: Optional[str] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    MiddleName: Optional[str] = None
    PhoneNumber: Optional[str] = None


class PhoneEnrichPostRequest(BaseModel):
    Phone: Optional[str] = None
